### ISSUE TITLE
doesn't work on OSX 10.10.5

### ISSUE THREAD

**Issue by drew1kun** [cocopon/atom-iceberg-syntax#1]
Does it work on OSX?
It just doesn't apply when I'm chosing it in Settings and sets to Atom Dark instead of actually applying iceberg theme... Was it converted from .tmTheme? Because when I try to convert my favourite Sublime themes I'm getting the same result... I'm wondering if it's a converter bug under osx or something else...

**Comment by cocopon** [comment]
Fmm...I use it on OS X 10.11.1 and it works fine. I made it from scratch.
Do you use the latest version of Atom?

**Comment by drew1kun** [comment]
I guess I know... I tried to install it with `git clone`... Installed with Package manager and it works.
Could you actually tell how to make my custom theme available as a atom package manager? Thanks!

**Comment by cocopon** [comment]
I referred to steps in the official document:
https://atom.io/docs/v1.2.3/hacking-atom-package-word-count#publishing

I think you should create a git repository for your theme at first.

I hope this will help :smiley:

**Comment by drew1kun** [comment]
Thanx
